membership_site/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('accounts/', include("allauth.urls")),
    path('paypal/', include('paypal.standard.ipn.urls')),
    

    # re_path(r'^checkout/paypal/', include('paypal.express.urls')),

]

users/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls import url
from .import views
from .views import *


app_name = 'users'
urlpatterns = [
        path('', index , name="index"),
        path('login/', login , name="login"),
        path('contactus/', contactus , name="contactus"),
        path('payment_details/', payment_details , name="payment_details"),
        path('signup/', signup , name="signup"),
        path('forgot-password/', forgot , name="forgot"),
        path('forgot-password-request/', requestcode , name="forget_password"),
        path('verify-password-request/', confirmcode , name="verify_code"),
        path('set-password/', set_password , name="set_password"),
        path('redirect-login/', login_again , name="login_again"),
        path('verify/payment/', verify_payment , name="verify-payment"),
        path('paypal-pay/', PaypalFormView.as_view(), name='paypal-pay'),
        path('paypal-sub/', PaypalSub, name='paypal-sub'),
        path('paypal-ips/', ips, name='paypal-ips'),
        path('process_subscription/', views.process_subscription, name='process_subscription'),
        path('paypal-return/', payment_success, name='paypal-return'),
        path('paypal-cancel/', PaypalCancelView.as_view(), name='paypal-cancel'),
]

users/forms.py
from allauth.account.forms import LoginForm, SignupForm
from django.forms import ModelForm
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from creditcards.forms import CardNumberField, CardExpiryField, SecurityCodeField
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from cities_light.models import City, Country, Region
from django.utils.translation import ugettext_lazy as _
import pytz

User = get_user_model()


class YourLoginForm(LoginForm):
    def __init__(self, *args, **kwargs):
        super(YourLoginForm, self).__init__(*args, **kwargs)
        self.fields['login'].widget.attrs.update(
            {'type': 'email', 'class': 'signup__input', 'placeholder': 'Email *'})
        self.fields['password'].widget.attrs.update(
            {'type': 'password', 'class': 'signup__input', 'placeholder': 'Password *'})


class CustomSignupForm(UserCreationForm):
    phone = forms.CharField(max_length=14)


    error_message = UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(UserCreationForm.Meta):
        model = User
        fields = [
            'email',
            'username',
            'password1',
            'phone',
            
        ]


    def __init__(self, *args, **kwargs):
        super(CustomSignupForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update(
                {'placeholder': field.title(), 'class': 'signup__input'})
        


    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])



class SubscriptionForm(forms.Form):
    plans = forms.ModelChoiceField(queryset=MembershipPlan.objects.all())

users/views.py
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.http import HttpResponse
from decimal import Decimal
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.urls import reverse , include
from django.contrib.auth.decorators import login_required
from cities_light.models import City, Country, Region
from .models import *
import os
from twilio.rest import Client
import pytz
from .models import User
import json
from django.http import JsonResponse
from datetime import date
from paypal.standard.forms import PayPalPaymentsForm
from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from .forms import *




import logging

from django.http import HttpResponse, QueryDict
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST

from paypal.standard.ipn.forms import PayPalIPNForm
from paypal.standard.ipn.models import PayPalIPN
from paypal.standard.models import DEFAULT_ENCODING
from paypal.utils import warn_untested

logger = logging.getLogger(__name__)

CONTENT_TYPE_ERROR = ("Invalid Content-Type - PayPal is only expected to use "
                      "application/x-www-form-urlencoded. If using django's "
                      "test Client, set `content_type` explicitly")

# @login_required
def index(request):
    if request.user.is_authenticated:
        return render(request, 'based.html', {})
    return render(request, 'homepage/home.html', {})

def payment(request):
    return render(request, 'payment_method.html', {})

def payment_details(request):
    return render(request, 'payment_details.html', {})

def contactus(request):
    if request.method == "GET":
        context = {}
        context['faq_list'] = FAQ.objects.all()
        return render(request, 'contactus.html', context)
    else:
        context = {}
        email = request.POST['email']
        message = request.POST['message']
        contact = Contact()
        try:
            contact.email = email
            contact.message = message
            contact.save()
            context['success'] = "Your message is received. We will Contact you soon!"
        except:
            context['fail'] = "OPS! We could not get your message. Please try again."
        return render(request, 'contact/contactus.html', context)

def login(request):
    return render(request, 'logine.html')

def signup(request):
    return render(request, 'index.html')


def forgot(request):
    return render(request, 'forgot_password.html')


def requestcode(request):
    if request.method == 'GET':
        return render(request, 'forgot_password.html')
    else:
        email = request.POST['email']
        phone = request.POST['phone']
        try:
            exist = User.objects.get(email=email)
            if(exist and exist.phone and phone and exist.phone == phone):
                request.session['email'] = email
                request.session['phone'] = exist.phone
            else:
                return render(request, 'forgot_password.html', {'error':'Phone does not match the user'})
        except:
            return render(request, 'forgot_password.html', {'error':'Credentials not correct.'})
    account_sid = 'AC25a06a6346e507691a44414a56dfd055'
    auth_token = '762bf7cce3514918e9c1dbe5c5c7931a'
    client = Client(account_sid, auth_token)
    try:
        verification = client.verify \
                            .services('VA7f2d07a28a78b9879da08b5875f66f50') \
                            .verifications \
                            .create(to=request.session['phone'], channel='sms')
    except:
        return render(request, 'forgot_password.html', {'error':'Incorrect phone number.'})
    return render(request, 'change_password.html')


def confirmcode(request):
    if request.method == 'GET':
        return render(request, 'change_password.html')
    else:
        code = request.POST['code']
        account_sid = 'AC25a06a6346e507691a44414a56dfd055'
        auth_token = '762bf7cce3514918e9c1dbe5c5c7931a'
        client = Client(account_sid, auth_token)
        verification = client.verify \
                                .services('VA7f2d07a28a78b9879da08b5875f66f50') \
                                .verification_checks \
                                .create(to=request.session['phone'], code=code)
        print(verification.status)
        if(verification.status == 'pending'):
            return render(request, 'change_password.html', {'error':'Verification code does not match. Please try again.'})
        return render(request, 'confirm_password.html')



def set_password(request):
    if request.method == 'GET':
        return render(request, 'confirm_password.html')
    else:
        try:
            user = User.objects.get(email=request.session['email'])
            print(request.session['email'])
            if(user):
                pass
            else:
                return render(request, 'confirm_password.html', {'error':'User not found. Connect Interrupted!'})
            del request.session['email']
            del request.session['phone']
        except:
            return render(request, 'confirm_password.html', {'error':'User not found. Connect Interrupted!'})
        p1 = request.POST['password1']
        p2 = request.POST['password2']
        if(p1 and p2 and p1 == p2):
            user.set_password(p1)
            user.save()
        else:
            return render(request, 'confirm_password.html', {'error':'Password fields do not match'})

        return redirect("login_again")


def login_again(request):
    return render(request, 'login_again.html')



def verify_payment(request):
    if request.method == 'GET':
        return render(request, 'confirm_password.html')
    else:
        context = {}
        card_number = json.loads(request.POST.get("card_number"))
        card_code = json.loads(request.POST.get("card_code"))
        card_expiry = json.loads(request.POST.get("card_expiry"))
        print(card_expiry)
        print(card_number)
        print(card_code)
        obj = CreditCard()
        try:
            obj.cc_code = card_code
            obj.card_number = card_number
            if(card_expiry>date.today().month):
                print("AAAAAAAAAAAAA")
            obj.card_expiry = date.today()
            context['success'] = "VERified"

        except:
            context['fail'] = "fail"

        # obj.save()
        return JsonResponse(context)




class PaypalFormView(FormView):
    template_name = 'paypal_form.html'
    form_class = PayPalPaymentsForm

    def get_initial(self):
        print(self.request.build_absolute_uri(reverse('paypal-ipn')))
        return {
            "business": settings.PAYPAL_RECEIVER_EMAIL,
            "amount": 20,
            "currency_code": "USD",
            "item_name": 'Example item',
            "invoice": 1234,
            "notify_url": self.request.build_absolute_uri(reverse('paypal-ipn')),
            "return_url": self.request.build_absolute_uri(reverse('users:paypal-return')),
            "cancel_return": self.request.build_absolute_uri(reverse('users:paypal-cancel')),
            "lc": 'EN',
            "no_shipping": '1',
        }




class PaypalCancelView(TemplateView):
    template_name = 'paypal_cancel.html'

@login_required
def PaypalSub(request):
    if request.method=="GET":
        context={
            'memberships': MembershipPlan.objects.all(),
            'form': SubscriptionForm()
        }
        return render(request, 'membership.html',context)
    else:
        request.session['plan_type'] = request.POST['sub']
        print(request.POST['sub'])
        return redirect('users:process_subscription')
    return render(request, 'paypal_success.html',{})


def process_subscription(request):
    membership_id = request.session.get('plan_type')
    mem_obj = None
    if membership_id:
        mem_obj = MembershipPlan.objects.get(id=membership_id)
    else:
        print("FALSE")
        return None
    price = mem_obj.monthly_price
    billing_cycle = 1
    billing_cycle_unit = "M"
    
    print(request.build_absolute_uri(reverse('users:paypal-ips')))
    paypal_dict  = {
        "cmd": "_xclick-subscriptions",
        'business': 'sb-mjtlg6191180@business.example.com',
        "a3": price,  # monthly price
        "p3": billing_cycle,  # duration of each unit (depends on unit)
        "t3": billing_cycle_unit,  # duration unit ("M for Month")
        "src": "1",  # make payments recur
        "sra": "1",  # reattempt payment on payment error
        "no_note": "1",  # remove extra notes (optional)
        'item_name': mem_obj.title,
        'custom': 122,     # custom data, pass something meaningful here
        "notify_url": 'https://516c5674add8.ngrok.io/paypal-ips/',
        "return_url": request.build_absolute_uri(reverse('users:paypal-return')),
        "cancel_return": request.build_absolute_uri(reverse('users:paypal-cancel')),
    }

    form = PayPalPaymentsForm(initial=paypal_dict, button_type="subscribe")
    return render(request, 'process_subscription.html', locals())





def ips(request):
    print("CALLING"*30)
    return HttpResponse("OKAY")



def payment_success(request):
    membership_id = request.session.get('plan_type')
    print('creating')
    print(membership_id)
    mem_obj = MembershipPlan.objects.get(id=membership_id)
    if(mem_obj):
        obj = Subscription()
        obj.membership = mem_obj
        obj.user = request.user
        obj.is_active = True
        obj.save()
    return render(request, 'paypal_success.html')

users/templates/change_password.html
  {% include 'head.html' %}   
  {% load static %}


  <style>
      
    .footer {
      left: 0;
      bottom: 0;
      width: 100%;
      background-color: #679141;
      color: white;
      text-align: center;
    }
   </style>
   
   <div class="bs-example">
       <nav class="navbar navbar-expand-md navbar-light " style="background-color: #679141">
           <a href="#" class="navbar-brand">
               <img src="{% static 'img/logo.png' %}" height="80" alt="NSMAR">
           </a>
           <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
               <span class="navbar-toggler-icon"></span>
           </button>
   
           <div class="collapse navbar-collapse" id="navbarCollapse">
               <div class="navbar-nav">
                   <a href="{% url 'account_signup' %}" class="nav-item nav-link active" style="color: white;">Become A Member</a>
               </div>
               <div class="navbar-nav ml-auto px-5">
                 <ul id="topnav" class="navbar-nav  w-100 justify-content-left px-1 py-2" >
                 <li class="nav-item" style="display: flex;align-items: flex-start;">
                   <a class="nav-link" href="#" style="color: white;">
                       Already A Member?  Call Us We Are Here To Serve You </a>  
   
                       <a class="nav-link" href="?" style="color: white;">
                           <strong style="text-decoration: underline;font-size: larger;"> 555 123 4567</strong> </a>  
                       
   
                 </li>                
                 </ul>
               </div>
           </div>
   
       </nav>
       <nav class="navbar navbar-expand-md navbar-light bg-light" style="margin-top: -1%; display: flex; align-items: flex-end;">
   
         <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar2Collapse">
             <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse  justify-content-left navbar-collapse" id="navbar2Collapse">
           <div class="navbar-nav d-flex justify-content-end">
               <a href="#" class="hovel nav-item nav-link active" style="padding-right: 35px;padding-left: 30px;">
                   Email us: 
                   <strong style="text-decoration: underline;"> sales@nsamr.ca </strong>
               </a>
           </div>
   
       </div>
         <div class="collapse  justify-content-end navbar-collapse" id="navbar2Collapse">
             <div class="navbar-nav d-flex justify-content-end" style="margin-right: 5%;">
   
               <li class="nav-item" style="display: flex;align-items: flex-start;">
                   <a class="nav-link" href="#" style="color: black;">
                       Not Yet A Member?  Call Us And Get The Help You Need </a>  
   
                       <a class="nav-link" href="?" style="color: black;">
                           <strong style="text-decoration: underline;font-size: larger;"> 145 145 1234 </strong> </a>  
                       
   
                 </li>   
             </div>
   
         </div>
   
     </nav>
   </div>
   
   








  <div class="container register">
    <div class="row">
        <div class="col-md-3 register-left">
            <img src="{% static 'img/logo.png' %}" alt=""/>
            <p>National Sales & Marketing Resources</p><br>
            <small>Already have an account?</small>
            <a href="{% url 'account_login' %}" name="" style="color: #3b5998;">Login</a><br/>
        </div>
        <div class="col-md-9 register-right">

            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <h3 class="login-heading">Email Verification</h3>
                    <form id="IndividualForm" method="POST" action="{% url 'users:verify_code' %}">
                        {% csrf_token %}
                    <div class="row register-form">
                        <div class="col-md-12">
                            <p style="color: rgb(219, 44, 44);">{{ error }}</p>
                            <div class="form-group">
                                <input type="text" name="code" class="form-control" placeholder="Enter Verification code" value="" required/>
                            </div>
                            <button type="submit" id="myBtn" class="btnlogin">Send Code</button>
                        </div>

                    </div>
                </form>
                </div>

            </div>
        </div>
    </div>

</div>	
<div class="d-flex flex-column" style="margin-top: 6%;">
    <nav>
    </nav>
    <main class="flex-fill">
    </main>
    <footer class="footer">
        <p>Copyright Protected - NSMAR</p>
    </footer>
</div>

users/templates/confirm_password.html
  {% include 'head.html' %}   
  {% load static %}

  <style>
      
    .footer {
      left: 0;
      bottom: 0;
      width: 100%;
      background-color: #679141;
      color: white;
      text-align: center;
    }
   </style>
   
   <div class="bs-example">
       <nav class="navbar navbar-expand-md navbar-light " style="background-color: #679141">
           <a href="#" class="navbar-brand">
               <img src="{% static 'img/logo.png' %}" height="80" alt="NSMAR">
           </a>
           <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
               <span class="navbar-toggler-icon"></span>
           </button>
   
           <div class="collapse navbar-collapse" id="navbarCollapse">
               <div class="navbar-nav">
                   <a href="{% url 'account_signup' %}" class="nav-item nav-link active" style="color: white;">Become A Member</a>
               </div>
               <div class="navbar-nav ml-auto px-5">
                 <ul id="topnav" class="navbar-nav  w-100 justify-content-left px-1 py-2" >
                 <li class="nav-item" style="display: flex;align-items: flex-start;">
                   <a class="nav-link" href="#" style="color: white;">
                       Already A Member?  Call Us We Are Here To Serve You </a>  
   
                       <a class="nav-link" href="?" style="color: white;">
                           <strong style="text-decoration: underline;font-size: larger;"> 555 123 4567</strong> </a>  
                       
   
                 </li>                
                 </ul>
               </div>
           </div>
   
       </nav>
       <nav class="navbar navbar-expand-md navbar-light bg-light" style="margin-top: -1%; display: flex; align-items: flex-end;">
   
         <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar2Collapse">
             <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse  justify-content-left navbar-collapse" id="navbar2Collapse">
           <div class="navbar-nav d-flex justify-content-end">
               <a href="#" class="hovel nav-item nav-link active" style="padding-right: 35px;padding-left: 30px;">
                   Email us: 
                   <strong style="text-decoration: underline;"> sales@nsamr.ca </strong>
               </a>
           </div>
   
       </div>
         <div class="collapse  justify-content-end navbar-collapse" id="navbar2Collapse">
             <div class="navbar-nav d-flex justify-content-end" style="margin-right: 5%;">
   
               <li class="nav-item" style="display: flex;align-items: flex-start;">
                   <a class="nav-link" href="#" style="color: black;">
                       Not Yet A Member?  Call Us And Get The Help You Need </a>  
   
                       <a class="nav-link" href="?" style="color: black;">
                           <strong style="text-decoration: underline;font-size: larger;"> 145 145 1234 </strong> </a>  
                       
   
                 </li>   
             </div>
   
         </div>
   
     </nav>
   </div>
   
   




  <div class="container register">
    <div class="row">
        <div class="col-md-3 register-left">
            <img src="{% static 'img/logo.png' %}" alt=""/>
            <p>National Sales & Marketing Resources</p><br>
            <small>Already have an account?</small>
            <a href="{% url 'account_login' %}" name="" style="color: #3b5998;">Login</a><br/>
        </div>
        <div class="col-md-9 register-right">

            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <h3 class="login-heading">Change Password</h3>
                    <form id="setpass" method="POST" action="{% url 'users:set_password' %}">
                        {% csrf_token %}
                    <div class="row register-form">
                        <div class="col-md-12">
                            <p style="color: rgb(219, 44, 44);">{{ error }}</p>
                            <div class="form-group">
                                <input type="password" id="pass1" name="password1" class="form-control" placeholder="Enter Password" value="" required/>
                            </div>
                            <div class="form-group">
                                <input type="password" id="pass2" name="password2" class="form-control" placeholder="Confirm Password" value="" required/>
                            </div>
                        </form>
                            <button onclick="validate();" id="myBtn" class="btnlogin">Set Password</button>
                            
                            <p id="error" style="color: rgb(219, 44, 44);"></p>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>

</div>	

<div class="d-flex flex-column" style="margin-top: 6%;">
    <nav>
    </nav>
    <main class="flex-fill">
    </main>
    <footer class="footer">
        <p>Copyright Protected - NSMAR</p>
    </footer>
</div>
<script>
function passwordIsValid(password){
    //>8 characters, atleast one small, atleast one capital, atleast one number, atleast one special character
    return !(/^(.{0,7}|[^0-9]*|[^A-Z]*|[^a-z]*|[a-zA-Z0-9]*)$/.test(password));
}

function validate(){
    var password1 = document.getElementById("pass1").value;
    var password2 = document.getElementById("pass2").value;
    if(!passwordIsValid(password1)){
        document.getElementById("error").innerHTML = "Password must have:\n Minimum 8 characters \n >1 small letter \n >1 capital letter \n >1 special case letter" ;
        return;
    }
    else if(password1 != password2){
        document.getElementById("error").innerHTML = "Passwords do not match." ;
        return;
    }
    else{
        document.getElementById("setpass").submit();
    }
}
</script>

users/templates/fp.html
  
  {% include 'head.html' %}   
  {% load static %}



  <style>
      
    .footer {
      left: 0;
      bottom: 0;
      width: 100%;
      background-color: #679141;
      color: white;
      text-align: center;
    }
   </style>
   
   <div class="bs-example">
       <nav class="navbar navbar-expand-md navbar-light " style="background-color: #679141">
           <a href="#" class="navbar-brand">
               <img src="{% static 'img/logo.png' %}" height="80" alt="NSMAR">
           </a>
           <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
               <span class="navbar-toggler-icon"></span>
           </button>
   
           <div class="collapse navbar-collapse" id="navbarCollapse">
               <div class="navbar-nav">
                   <a href="{% url 'account_signup' %}" class="nav-item nav-link active" style="color: white;">Become A Member</a>
               </div>
               <div class="navbar-nav ml-auto px-5">
                 <ul id="topnav" class="navbar-nav  w-100 justify-content-left px-1 py-2" >
                 <li class="nav-item" style="display: flex;align-items: flex-start;">
                   <a class="nav-link" href="#" style="color: white;">
                       Already A Member?  Call Us We Are Here To Serve You </a>  
   
                       <a class="nav-link" href="?" style="color: white;">
                           <strong style="text-decoration: underline;font-size: larger;"> 555 123 4567</strong> </a>  
                       
   
                 </li>                
                 </ul>
               </div>
           </div>
   
       </nav>
       <nav class="navbar navbar-expand-md navbar-light bg-light" style="margin-top: -1%; display: flex; align-items: flex-end;">
   
         <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar2Collapse">
             <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse  justify-content-left navbar-collapse" id="navbar2Collapse">
           <div class="navbar-nav d-flex justify-content-end">
               <a href="#" class="hovel nav-item nav-link active" style="padding-right: 35px;padding-left: 30px;">
                   Email us: 
                   <strong style="text-decoration: underline;"> sales@nsamr.ca </strong>
               </a>
           </div>
   
       </div>
         <div class="collapse  justify-content-end navbar-collapse" id="navbar2Collapse">
             <div class="navbar-nav d-flex justify-content-end" style="margin-right: 5%;">
   
               <li class="nav-item" style="display: flex;align-items: flex-start;">
                   <a class="nav-link" href="#" style="color: black;">
                       Not Yet A Member?  Call Us And Get The Help You Need </a>  
   
                       <a class="nav-link" href="?" style="color: black;">
                           <strong style="text-decoration: underline;font-size: larger;"> 145 145 1234 </strong> </a>  
                       
   
                 </li>   
             </div>
   
         </div>
   
     </nav>
   </div>
   
   



  <div class="container register">
    <div class="row">
        <div class="col-md-3 register-left">
            <img src="{% static 'img/logo.png' %}" alt=""/>
            <p>National Sales & Marketing Resources</p><br>
            <small>Already have an account?</small>
            <a href="{% url 'account_login' %}" name="" style="color: #3b5998;">Login</a><br/>
        </div>
        <div class="col-md-9 register-right">

            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <h3 class="login-heading">Email Verification</h3>
                    <form id="IndividualForm" method="POST" action="{% url 'users:forget_password' %}">
                        {% csrf_token %}
                    <div class="row register-form">
                        <div class="col-md-12">
                            <p style="color: rgb(219, 44, 44);">{{ error }}</p>
                            <div class="form-group">
                                <input type="text" name="email" class="form-control" placeholder="Email *" value="" required/>
                            </div>
                            
                            <div class="form-group">
                                <input type="text" name="phone" class="form-control" placeholder="Enter Phone number *" value="" required/>
                            </div>
                            <button type="submit" id="myBtn" class="btnlogin">Verify Account</button>
                        </div>

                    </div>
                </form>
                </div>

            </div>
        </div>
    </div>

</div>	

<div class="d-flex flex-column" style="margin-top: 6%;">
    <nav>
    </nav>
    <main class="flex-fill">
    </main>
    <footer class="footer">
        <p>Copyright Protected - NSMAR</p>
    </footer>
</div>

users/templates/paypal_cancel.html
cancelled

users/templates/paypal_form.html
<html>
  <body>
    {{ form.render }}
  </body>
</html>

users/templates/paypal_success.html
success

users/templates/process_subscription.html
{% block title %}Pay using PayPal{% endblock %}
{% block content %}
    <h4>Subscribe using PayPal</h4>
    {{ form.render }}
{% endblock %}

users/templates/select_membership.html
<form method="POST" action="{% url 'users:paypal-sub'  %}">
    {% csrf_token %}
    {{form}}
    <button type="submit">Submit</button>
</form>