membership_site/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('accounts/', include("allauth.urls")),
    path('paypal/', include('paypal.standard.ipn.urls')),
    

    # re_path(r'^checkout/paypal/', include('paypal.express.urls')),

]

users/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls import url
from .import views
from .views import *


app_name = 'users'
urlpatterns = [
        path('', index , name="index"),
        path('login/', login , name="login"),
        path('contactus/', contactus , name="contactus"),
        path('payment_details/', payment_details , name="payment_details"),
        path('signup/', signup , name="signup"),
        path('forgot-password/', forgot , name="forgot"),
        path('forgot-password-request/', requestcode , name="forget_password"),
        path('verify-password-request/', confirmcode , name="verify_code"),
        path('set-password/', set_password , name="set_password"),
        path('redirect-login/', login_again , name="login_again"),
        path('verify/payment/', verify_payment , name="verify-payment"),
        path('paypal-pay/', PaypalFormView.as_view(), name='paypal-pay'),
        path('paypal-sub/', PaypalSub, name='paypal-sub'),
        path('paypal-ips/', ips, name='paypal-ips'),
        path('process_subscription/', views.process_subscription, name='process_subscription'),
        path('paypal-return/', payment_success, name='paypal-return'),
        path('paypal-cancel/', PaypalCancelView.as_view(), name='paypal-cancel'),
]

templates/homepage/base.html
{% load static %}
{% include "homepage/head.html" %}
<body class="cnt-home">

{% include "homepage/navbar.html" %}
{% block content %}
{% endblock content %}



{% include "homepage/footer.html" %}

<!-- JavaScripts placed at the end of the document so the pages load faster --> 
<!-- JavaScripts placed at the end of the document so the pages load faster --> 
<script src=" {% static 'assets/js/jquery-1.11.1.min.js' %} "></script> 
<script src=" {% static 'assets/js/bootstrap.min.js' %} "></script> 
<script src=" {% static 'assets/js/bootstrap-hover-dropdown.min.js' %} "></script>
<script src="https://kit.fontawesome.com/c2bb281b83.js" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</body>

</html>

templates/homepage/footer.html
{% load static %}
  <footer class="mainfooter" role="contentinfo">
  <div class="footer-middle">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6">
        <!--Column1-->
        <div class="footer-pad">
          <h4>Quick Links</h4>
          <ul class="list-unstyled">
            <li>Contact</li>
            <li>Fees</li>
            <li>Security</li>
            <li>About</li>
            <li style="padding-bottom:15px">Developers</li>
          </ul>
        </div>
      </div>

    	<div class="col-md-3 alu" >
    		<h4>Follow Us</h4>
            <ul class="social-network social-circle">
             <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
             <li><a href="#" class="icontwitter" title="Linkedin"><i class="fa fa-twitter"></i></a></li>
             <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
             <li><a href="#" class="iconyoutube" title="Linkedin"><i class="fab fa-youtube"></i></a></li>
            </ul>				
		</div>
    </div>
	<div class="row">
		<div class="col-md-12 copy">
			<p class="text-center">&copy; Copyright 2021 -  All rights reserved.</p>
		</div>
	</div> 
</footer>


 

templates/homepage/head.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
<!-- Meta -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="Rose Smith">
<meta name="keywords" content="Marketing, Products, Branding, Sales">
<meta name="robots" content="all">
<title>Nsamr</title>

<!-- Bootstrap Core CSS -->
<link rel="stylesheet" href=" {% static 'assets/css/bootstrap.min.css' %} ">

<!-- Customizable CSS -->
<link rel="stylesheet" href=" {% static 'assets/css/main.css' %} ">
<link rel="stylesheet" href=" {% static 'assets/css/accounts.css' %} ">




</head>

templates/homepage/home.html
{% extends 'homepage/base.html' %}
{% load static %}

{% block content %}

<style>
  .modal.custom .modal-dialog {
    width:30%;
    position:fixed;
    bottom:0;
    right:0;
}
@media (min-width: 768px) and (max-width: 991px) {
  .modal.custom .modal-dialog {
    width: 50%;
    position: fixed;
    bottom: 0;
    right: 0;
}
}
@media only screen and (max-width: 767px) {
  .modal.custom .modal-dialog {
    width: 95%;
    position: fixed;
    bottom: 0;
    right: 0;
}
}
</style>

<div class="body-content outer-top-vs" id="top-banner-and-menu" >
  <div class="container-fluid wide1" >
    <div class="col-lg-7 distance">
     <h1 style="margin-top:0px; font-size: 42px;font-weight: bold;">
     <span style="color: rgb(73, 72, 72);">We help Anyone, Anywhere,<br></span>
            <span style="color: rgb(73, 72, 72);">Any business sell more<br></span>
            <span style="color: rgba(21, 138, 21, 0.767);">Be successful</span>
     </h1><br>
     <form method="GET" action="" role="search"  class="form-search">
                <input  placeholder="Enter your email address here..."  name="srch- {% static 'term" id="srch' %} -term" type="text" />
                <span> <button class="bt1">Start Free Trial</button></span>
            </form>
     <br>
        <p class="p1">
            
            Try NATIONAL SALES AND MARKETING RESOURCES nsmar.ca free for 7 days.
            By entering your email, you agree to receive marketing emails from 
            NATIONAL SALES AND MARKETING RESOURCES nsmar.ca

          </p>
     </div>
     <div class="col-sm-4 wid" >
     <img style="max-height:400px;width:100%" src="https://images.unsplash.com/39/lIZrwvbeRuuzqOoWJUEn_Photoaday_CSD%20(1%20of%201)-5.jpg?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80">
     </div>
    </div>

    <div class="modal custom" style="margin-bottom: 8%;"   id="trackModal" tabindex="-1" role="dialog" aria-labelledby="trackModalLabel" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
  
              <div class="modal-header" style="font-family: 'Circular-Loom';">
              <button type="button" class="close" onclick="hideModal();" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h3 class="getlaid" id="trackModalLabel" style="margin:0px">
                    <b>Want free advertisement and help for your business?</b>
                  </h3>
  
              </div>
  
              <div class="modal-footer" style="padding:5px 15px 5px 15px">
                  <div class="btnmodal" data-dismiss="modal">
                    <a class="btn pointer" style="color: gray;" data-dismiss="modal">Skip Trial</a>
                    <a href="{% url 'account_signup' %}" class="btn pointer" style="color: #679141;font-size:16px" data-dismiss="modal">7 DAYS FREE</a>
                </div>
  
              </div>
          </div>
      </div>
  </div>
  </div>

</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script>

  $(document).ready(function() {
  setTimeout(function() {
    $('#trackModal').addClass("show");
  }, 5000);
    });
  function hideModal(){
    $('#trackModal').removeClass("show");

  }
  
</script>
{% endblock content %}

templates/homepage/navbar.html
{% load static %}
<header class="header-style-1"> 
  
  <!-- ============================================== TOP MENU ============================================== -->
  <div class="top-bar animate-dropdown" style="background-color:white;">
    <div class="container">
      <div class="header-top-inner">
       <h4> <i class="fas fa-exclamation-triangle fa-lg" style="color:rgb(182, 0, 0);"></i>
        Do you want more customers? <button class="responsive1" id="button1"> YES, I WANT MORE CUSTOMERS</button>
        <a style="text-decoration: underline;"></a><span class="head1">NO, I HAVE ENOUGH CUSTOMERS</span></h4>

      </div>
    </div>
  </div>
  <!-- /.header-top --> 
  <!-- ============================================== TOP MENU : END ============================================== -->
  <div class="main-header">
      <div class="row">
          <div class="logo"> 
             <div class="col-lg-7 col-md-6 col-sm-8 col-xs-12 top-search-holder pad1"> 
                 <h2 style="margin-top: 20px;">NATIONAL SALES AND MARKETING RESOURCES</h2>
             </div>    
             <div class="ok col-sm-4" style="font-size:15px">
                <p >We are here to help you, Call us now <b>1-888-631-5556</b></p>
                <p>Please tell us how can we help you, We are here to help you <b>sales@nsamr.com</b></p>
                <i class="fab fa-facebook fa-1x"></i>&ensp;
                <i class="fab fa-twitter  fa-1x"></i>&ensp;
                <i class="fab fa-linkedin-in fa-1x "></i>&ensp;
                <i class="fab fa-youtube fa-1x "></i>
            </div>
           </div>
          
    </div>
  </div>
 
  <!-- ============================================== NAVBAR ============================================== -->
  <div class="header-nav">
    <div class="container" style="width: 100%;">
      <div class="yamm navbar navbar-default" role="navigation">
      <div class="navbar-header">
       <button data-target="#mc-horizontal-menu-collapse" data-toggle="collapse" class="navbar-toggle collapsed" type="button"> 
       <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
       <div class="hid_desktop">
                <h2>NSAMR</h2>
        </div>
        </div>
        <div class="nav-bg-class">
          <div class="navbar-collapse collapse" id="mc-horizontal-menu-collapse">
            <div class="nav-outer">
              <ul class="nav navbar-nav">
                <li class="dropdown" > <a data-hover="dropdown"  href="{% url 'users:index' %}" target="logo">NSAMR</a> </li>
                <li class="dropdown" > <a data-hover="dropdown"  href="#" target="vbar1">Who are we</a> </li>
                <li class="dropdown" > <a data-hover="dropdown"  href="#" target="vbar1">What we do </a> </li>
                <li class="dropdown"> <a data-hover="dropdown"   target="vbar1">Become a member</a> </li>
                <li class="dropdown"> <a data-hover="dropdown"  href="#" target="vbar1">Get help and benefits</a> </li>
                <li class="dropdown"> <a data-hover="dropdown"  href="#" target="vbar1">Sell More</a> </li>
                <li class="dropdown"> <a data-hover="dropdown"  href="#" target="vbar2">Market</a> </li>
                <li class="dropdown"> <a data-hover="dropdown"  href="#" target="vbar">Pricing</a> </li>
                <li class="dropdown"> <a data-hover="dropdown"  onclick="javascript:window.location.href='{% url "users:contactus" %}';" target="vbar">Contact Us</a> </li>
                <li class="dropdown"> <a data-hover="dropdown"  href="#" target="vbar">Blog</a> </li>
                <li class="dropdown"> <a data-hover="dropdown"  href="#" target="vbar3">FAQs</a> </li>
                <li class="dropdown contact"> <a data-hover="dropdown"  onclick="javascript:window.location.href='{% url "account_login" %}';"  target="_blank"><i class="fa fa-user" style="color: #0ea55f;"></i> login</a> </li>
                <li class="dropdown">
                 <button target="_blank1" class="bt1 btn btn-success" >Start free trial</button> </li>
                
              </ul>
              <!-- /.navbar-nav -->
              <div class="clearfix"></div>
            </div>
            <!-- /.nav-outer --> 
          </div>
          <!-- /.navbar-collapse --> 
          
        </div>
        <!-- /.nav-bg-class --> 
      </div>
      <!-- /.navbar-default --> 
    </div>
    <!-- /.container-class --> 
    
  </div>
  <!-- /.header-nav --> 
  <!-- ============================================== NAVBAR : END ============================================== --> 
  
</header>