membership_site/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('accounts/', include("allauth.urls")),
    path('paypal/', include('paypal.standard.ipn.urls')),
    

    # re_path(r'^checkout/paypal/', include('paypal.express.urls')),

]

users/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls import url
from .import views
from .views import *


app_name = 'users'
urlpatterns = [
        path('', index , name="index"),
        path('login/', login , name="login"),
        path('contactus/', contactus , name="contactus"),
        path('payment_details/', payment_details , name="payment_details"),
        path('signup/', signup , name="signup"),
        path('forgot-password/', forgot , name="forgot"),
        path('forgot-password-request/', requestcode , name="forget_password"),
        path('verify-password-request/', confirmcode , name="verify_code"),
        path('set-password/', set_password , name="set_password"),
        path('redirect-login/', login_again , name="login_again"),
        path('verify/payment/', verify_payment , name="verify-payment"),
        path('paypal-pay/', PaypalFormView.as_view(), name='paypal-pay'),
        path('paypal-sub/', PaypalSub, name='paypal-sub'),
        path('paypal-ips/', ips, name='paypal-ips'),
        path('process_subscription/', views.process_subscription, name='process_subscription'),
        path('paypal-return/', payment_success, name='paypal-return'),
        path('paypal-cancel/', PaypalCancelView.as_view(), name='paypal-cancel'),
]

templates/based.html
    {% include 'head.html' %}
    
{% load static %}
<style>
  body{
    background: url('{% static "img/marketing.jpg" %}') no-repeat center center fixed; 
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
  }
  
 .footer {
   position: fixed;
   left: 0;
   bottom: 0;
   width: 100%;
   background-color: #679141;;
   color: white;
   text-align: center;
 }
 .dropdown:hover > .dropdown-menu {
    display: block;
}
.dropdown > .dropdown-toggle:active {
    /*Without this, clicking will make it sticky*/
    pointer-events: none;
}
.hovel:hover{
  color:white;
  background-color: #3b5898bb;
}


</style>
<script> 

function submitform(){
  $("#logform").submit();
}


</script>
    <body>

      <div class="bs-example">
        <nav class="navbar navbar-expand-md navbar-light " style="background-color: #679141;">
            <a href="#" class="navbar-brand">
                <img src="{% static 'img/logo.png' %}" height="80" alt="NSMAR">
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav">
                    <a href="#" class="nav-item nav-link active" style="color: white;">Basic Membership</a>
                </div>
                <div class="navbar-nav ml-auto px-5">
                  <ul id="topnav" class="navbar-nav  w-100 justify-content-left px-1 py-2" >
                  <li class="nav-item">
                    <a class="nav-link" href="http://example.com" style="color: white;">
                      Help
                    </a>

                  </li>                
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" style="color: white;padding-bottom: 15px;" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      John Smith
                    </a>
                    <div id="topnavdropdown" class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" >
                      <a class="dropdown-item" href="#">Message Center</a>
                      <a class="dropdown-item" href="#">Profile Settings</a>
                      <form id="logform" method="post" action="{% url 'account_logout' %}">
                        {% csrf_token %}
                        {% if redirect_field_value %}
                        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
                        {% endif %}
                        <!-- <button  class="nav-link" style="background-color: orangered;"  type="submit">Logout</button> -->
                      </form>
                      <a class="dropdown-item"  href="javascript:submitform();">Log out</a>
                      
                    </div>
                  </li>
                  </ul>
                </div>
            </div>
  
        </nav>
        <nav class="navbar navbar-expand-md navbar-light bg-light" style="margin-top: -1%;">

          <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar2Collapse">
              <span class="navbar-toggler-icon"></span>
          </button>
  
          <div class="collapse navbar-collapse" id="navbar2Collapse">
              <div class="navbar-nav">
                  <a href="#" class="hovel nav-item nav-link active" style="padding-right: 35px;padding-left: 30px;">Home</a>
                  <a href="#" class="hovel nav-item nav-link" style="padding-right: 35px;">Activity</a>
                  <a href="#" class="hovel nav-item nav-link" style="padding-right: 35px;">Products & Services</a>
                  <a href="#" class="hovel nav-item nav-link" style="padding-right: 35px;">Marketing for Growth</a>
              </div>

          </div>

      </nav>
    </div>



    <div class="footer">
      <p>Copyright Protected - NSMAR</p>
    </div>

    </body>

templates/contactus.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
<!-- Meta -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<meta name="keywords" content="MediaCenter, Template, eCommerce">
<meta name="robots" content="all">
<title>Nsamr</title>
   <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">

<!-- Bootstrap Core CSS -->
<link rel="stylesheet" href=" {% static 'assets/css/bootstrap.min.css' %} ">

<!-- Customizable CSS -->
<link rel="stylesheet" href=" {% static 'assets/css/contact.css' %} ">

<script src="https://kit.fontawesome.com/c2bb281b83.js" crossorigin="anonymous"></script>
<style>


.widget-list {
  li {
    a {
      &:hover {
        text-decoration: underline;
      }
    }
  }
}
.widget {
  .card-header {
    background: #fff;
    a {
      width: 100%;
      display: block;
      &:after {
        content: "+";
        position: absolute;
        right: 40px;
        top: .9rem;
        transition: transform .25s ease-in-out;
      }
      &:hover,
      &:focus {
      text-decoration: none;
      }
      &[aria-expanded="true"] {
        &:after {
          transform: rotate(45deg);
        }
      }
    }
  }
  .card-block {
    padding: 0 1.3rem;
    .widget-list {
      li {
        margin-bottom: 4px;
      }
    }
  }
}
</style>
</head>
<body class="cnt-home">

<header class="header-style-1"> 
    <div class="top-bar animate-dropdown" style="background-color:#679141;">
      <div class="top3">
            <span class="top1 hid">NATIONAL SALES AND MARKETING RESOURCES </span>
            <span class="top2" >support@nsamr.com | (888) 123-9670</span>
            
      </div>
        

  </div>
  <div class="header-nav">
    <div class="container con" style="width: 100%;">
      <div class="yamm navbar navbar-default" role="navigation">
      <div class="navbar-header">
       <button data-target="#mc-horizontal-menu-collapse" data-toggle="collapse" class="navbar-toggle collapsed" type="button"> 
       <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        <div class="hid_desktop">
                <h2>NSAMR</h2>
        </div>
        </div>
        
        <div class="nav-bg-class">
          <div class="navbar-collapse collapse" id="mc-horizontal-menu-collapse">
           
              <ul class="nav_css nav navbar-nav " style="float:left">
                <li class="dropdown" > <a data-hover="dropdown"  href="#" target="logo">NSAMR</a> </li>
                <li class="dropdown" > <a data-hover="dropdown"  href="#" target="vbar1">Who are we</a> </li>
                <li class="dropdown" > <a data-hover="dropdown"  href="#" target="vbar1">What we do </a> </li>
                <li class="dropdown"> <a data-hover="dropdown"  href="#" target="vbar1">Become a member</a> </li>
                <li class="dropdown"> <a data-hover="dropdown"  href="#" target="vbar1">Get help and benefits</a> </li>
                <li class="dropdown"> <a data-hover="dropdown"  href="#" target="vbar1">Sell More</a> </li>
                <li class="dropdown"> <a data-hover="dropdown"  href="#" target="vbar2">Market</a> </li>
                <li class="dropdown p4"> <a data-hover="dropdown"  href="#" target="vbar">Pricing</a> </li>
                <li class="dropdown"> <a data-hover="dropdown" onclick="javascript:window.location.href='{% url "users:contactus" %}';"  target="vbar">Contact Us</a> </li>
                <li class="dropdown"> <a data-hover="dropdown"  href="" target="vbar">Blog</a> </li>
                <li class="dropdown "> <a data-hover="dropdown"  href="" target="vbar3">FAQs</a> </li>
                <li class="hid_mobile dropdown p3 contact "> <a data-hover="dropdown" onclick="javascript:window.location.href='{% url "account_login" %}';"   target="_blank"><i class="fa fa-user" style="color: #679141;"></i> login</a> </li>
                <li class=" hid_mobile dropdown ">
                 <button target="_blank1" class="bt1 btn btn-success" >Start free trial</button> </li>
                
              </ul>
             
            
            <!-- /.nav-outer --> 
          </div>
          <!-- /.navbar-collapse --> 
          
        </div>
        <!-- /.nav-bg-class --> 
      </div>
      <!-- /.navbar-default --> 
    </div>
    <!-- /.container-class --> 
    
  </div>

  <!-- /.header-top --> 
  <!-- ============================================== TOP MENU : END ============================================== -->
  <div class="main-header">
      <div class="row">
          <div class="logo"> 
             <div class="col-lg-7 col-md-6 col-sm-8 col-xs-12 top-search-holder pad1 h1"> 
                 <p>Help Center</p>
             </div>    
             <div class=" col-sm-4 h2">
                <p>Contact Customer Service</p>
            </div>
             <div class="col-lg-2" >
                <p class="first">Community Forum</p>
                <p>Resolution Forum</p>
                <p>Message Centre</p>
            </div>
           </div>
          
    </div>
  </div>

  
</header>
<script>
function showSib(sib_id){
    console.log("#");
    $("#"+sib_id).toggle();
    $("#"+sib_id).attr({
    "display" : "block",
  });
}
</script>
<div class="body-content outer-top-vs" id="top-banner-and-menu" >
  <div class="container-fluid">
  <div class="tapa2 cardcss ">
    <div class="card text-white bg-success mb-3 ">
        <span class="card-header"> <span class="blink" style="color:black;margin-left:5px">	&dArr;</span > &nbsp;We are Available!</span>
             <div class="card-body">
                  <p class="card-text"><span class="blink" style="color:white;">&#9658</span> We have active Facebook, Twitter, Instagram, and YouTube pages.
                  <br><span class="blink" style="color:white;">&#9658</span> You can reach Customer Service by email at <b style="font-style: italic;">support@nsamr.com</b> by phone at <b style="font-style: italic;"> (888) 123-9670</b></p>
             </div>
        </div>
    </div>
  <span class="block1">We Are Here For You When You Need Us </span>
    <div class="tid">

   <p class="h6">Tell us about your issue so we can help you more quickly.</p>
        <div id="searchBox" class="mobile-form">
            <form action="{% url 'users:contactus' %}" method="POST" class="search-form" id="searchform">
              {% csrf_token %}
                <input id="sbox" name="email" placeholder="Email" type="text" x-webkit-speech="" required><br>
                <textarea id="sbox" name="message" placeholder="Type your message here..." type="text" x-webkit-speech="" required></textarea><br>
                <button class="btn btn-success btn-lg btn-block" type="submit">Submit</button>
                <p style="color: #0f8d52;">{{success}}</p>
                <p style="color: red;">{{fail}}</p>
            </form>
        </div>
        <h3 class="center" style="font-weight:bold">Common Issues</h3>
        <hr>

   
            <h2 class="sr-only">Solodev Content Management System</h2>
            <ul class="list1">
              {% for faq in faq_list %}
              <li>
                <div id="accordion" role="tablist" aria-multiselectable="true" class="widget hidden-sm-up">
                  <div role="tab" id="headingOne">
                      <button class="expand1" data-toggle="collapse"  data-parent="#accordion" href="#collapse{{faq.id}}" aria-expanded="false" aria-controls="collapse{{faq.id}}">
                        {{faq.title}}
                      </button><hr>
                  <div id="collapse{{faq.id}}" class="collapse" role="tabpanel" aria-labelledby="headingOne">
                    <div class="card-block">
                      </h4>{{faq.description}}</h4>
                    </div>
                    <hr>
                  </div>
                </div>
              </div>
            </li>
              {% endfor %}

            </ul>

        <div class="info">
        <h1 class="hd2">NATIONAL SALES AND MARKETING RESOURCES </h1><span>has a very transparent Customer Service Policy.</span><br>
        <span>You can reach Customer Service by E-Mail at <b>support@nsamr.com</b> by phone at <b>(888) 123-9670.</b></span><br><br><br>
        <h1 class="hd1">Other ways to contact us</h1>
        <ul class="float">
        <li>
        <span class="icon-chat">
        </span>
        <p> support@nsamr.com</p>
        </li>
         <li>
         <span class="icon-resolution"></span>
        <p>Resolve transaction or account issues</p>
         </li>
        <li>
        <span class="icon-callus">
        </span>
        <p>(888) 123-9670</p>
        </li>
         <li>
         <span class="icon-community">
        </span>
        <p>Resolve transaction or account issues</p>
         </li>
        </ul>
        

    </div><br><br>

    <br>

    <br>
    <br>
</div>
 </div>
    <div class="footer">
       <footer class="mainfooter" role="contentinfo">
  <div class="footer-middle">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6">
        <!--Column1-->
        <div class="footer-pad">
          <h4>Quick Links</h4>
          <ul class="list-unstyled">
            <li>Contact</li>
            <li>Fees</li>
            <li>Security</li>
            <li>About</li>
            <li style="padding-bottom:15px">Developers</li>
          </ul>
        </div>
      </div>

    	<div class="col-md-3 alu" >
    		<h4>Follow Us</h4>
            <ul class="social-network social-circle">
             <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
             <li><a href="#" class="icontwitter" title="Linkedin"><i class="fa fa-twitter"></i></a></li>
             <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
             <li><a href="#" class="iconyoutube" title="Linkedin"><i class="fab fa-youtube"></i></a></li>
            </ul>				
		</div>
    </div>
	<div class="row">
		<div class="col-md-12 copy">
			<p class="text-center">&copy; Copyright 2021 -  All rights reserved.</p>
		</div>
	</div> 
    </div>

<!-- JavaScripts placed at the end of the document so the pages load faster --> 
<script src=" {% static 'assets/js/jquery-1.11.1.min.js' %} "></script> 
<script src=" {% static 'assets/js/bootstrap.min.js' %} "></script> 
</body>

</html>

templates/membership.html
{% extends "homepage/base.html" %}
{% load static %}

{% block content %}
<style>
:root {
  --red: #fe1609;
  --orange: #ff702e;
  --white: #f6f7f8;
  --dark: #5b5f6a;
  --dark-grey: #9ca5ae;
  --grey: #efefef;
}

html {
  box-sizing: border-box;
  font-family: "Montserrat", sans-serif;
  color: var(--dark);
  font-size: 16px;
}

*,
*:before,
*:after {
  box-sizing: inherit;
}

* {
  margin: 0;
  padding: 0;
}

body {
  background-color: var(--white);
  min-width: 200px;
}

.pricing-table {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

.pricing-table h2 {
  margin: 15px;
  font-weight: 700;
  font-size: 3.5rem;
}

.container_m {
  display: flex;
  justify-content: space-between;
  align-items: center;
  width: 90%;
  margin: 0 0;
}

.pricing-table .element {
  border: 1px solid var(--dark-grey);
  border-radius: 12px;
  width: 100%;
  margin: 20px;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  justify-content: space-around;
  align-items: center;
  font-size: 1.1rem;
  background-color: var(--white);
}

.element > * {
  margin: 10px;
}
.element{
    height:480px
}



.element .info h2 {
  text-align: center;
}

.element .info p {
  text-align: center;
  margin: 0 20px;
  font-size: 1.2rem;
}

.element .price {
  font-size: 4rem;
  font-weight: 700;
}

.element .period {
  display: flex;
  flex-direction: row;
  justify-content: space-around;
  background-color: var(--grey);
  padding: 0.5rem;
  border-radius: 8px;
  color: var(--dark);
}

.element .period label {
  flex: 1 1 50%;
  text-align: center;
  padding: 0.5rem 2rem;
  cursor: pointer;
}

.element .period label:hover {
  text-decoration: underline;
}

.period input[type="radio"] {
  display: none;
}

.period input[type="radio"]:checked + label {
  font-weight: 700;
  background-color: var(--white);
  border-radius: 6px;
}

.element ul {
  font-size: 1.2rem;
  list-style-type: none;
}

.element ul li {
  margin: 0.5rem;
}

.element ul li::before {
  content: url("https://karolnowinski.pl/assets/check-mark.svg");
  display: inline-block;
  margin: 0 10px;
  width: 1em;
  height: auto;
}

.element button {
  border: 0;
  background-color: var(--white);
  font-size: 1.4rem;
  color: var(--dark);
  border: 1px solid var(--dark);
  border-radius: 8px;
  padding: 10px 30px;
  margin: 20px;
  font-weight: 700;
  cursor: pointer;
}

.element button:hover {
  text-decoration: none;
  box-shadow: 2px 2px 0px var(--dark);
}

.element button:focus {
  outline-color: var(--dark);
}

.active {
  background: linear-gradient(135deg, var(--red), var(--orange));
  color: var(--white);
  border: 1px solid transparent !important;
}

.active ul li::before {
  content: url("https://karolnowinski.pl/assets/check-mark-white.svg");
}

.active button {
  border-color: transparent;
}

@media only screen and (max-width: 1500px) {
  html {
    font-size: 10px;
  }
}

@media only screen and (max-width: 1080px) {
  .container_m {
    flex-direction: column;
  }

  .element {
    margin: 20px 0;
  }

  .element:nth-of-type(2) {
    transform: scale(1);
  }

  .element ul {
    display: flex;
    justify-content: space-around;
    margin: 0 20px;
    text-align: center;
    flex-wrap: wrap;
  }

  .period {
    flex-wrap: wrap;
  }
}

</style>
<section class="pricing-table">
    <h2>Members Pay Less, Get More!</h2>
  <div class="container_m">
    <div class="element" >
      <div class="info">
        <h2>ESSENTIALS</h2>
        <p>Become a member of a select group of individuals who enjoy exclusive benefits across all our services and products.</p>
      </div>
      <span class="price">$100</span>
      <div class="period">
        <input type="radio" name="period" id="monthly" value="$12" checked />
        <label for="monthly">Monthly</label>
        <input type="radio" name="period" id="annualy" value="$8" />
        <label for="annualy">Annually</label>
      </div>
      <ul>
        <li>Unlimited listings</li>
        <li>Simple Analytics</li>
        <li>1 Account</li>
        <li>Branded with Lorem</li>
      </ul>
      <form action="{% url 'users:paypal-sub' %}" method="POST">
        {% csrf_token %}
        <input value="Click" name="sub" value="4" hidden/>
        <button name="sub" value="1" style="color:white;background-color:black" type="submit">Register!</button>
      </form>
    </div>
    <div class="element" style="color:#BBA31F;">
      <div class="info">
        <h2>GOLD</h2>
        <p>Our Gold membership programme offers an array of perks and benefits, exclusively designed to make your experiences with us more rewarding</p>
      </div>
      <span class="price">$199</span>
      <div class="period">
        <input type="radio" name="period" id="monthly" value="$12" checked />
        <label for="monthly">Monthly</label>
        <input type="radio" name="period" id="annualy" value="$8" />
        <label for="annualy">Annually</label>
      </div>
      <ul>
        <li>Unlimited listings</li>
        <li>Advanced Analytics</li>
        <li>More Services</li>
        <li>White Labels</li>
      </ul>
      <form action="{% url 'users:paypal-sub' %}" method="POST">
        {% csrf_token %}
        <input value="Click" name="sub" value="4" hidden/>
        <button name="sub" value="2" style="color:white;background-color:#DDB000" type="submit">Register!</button>
      </form>
    </div>
    <div class="element" style="color:#818a9d;">
      <div class="info">
        <h2>PLATINUM</h2>
        <p>Get exclusive packages and services with 24/7 support in Premium membership also with renew option</p>
      </div>
      <span class="price">$549</span>
      <div class="period">
        <input type="radio" name="period" id="monthly" value="$12" checked />
        <label for="monthly">Monthly</label>
        <input type="radio" name="period" id="annualy" value="$8" />
        <label for="annualy">Annually</label>
      </div>
      <ul>
        <li>All Platinum Capabilities</li>
        <li>Customized Analytics</li>
        <li>Customized Account</li>
        <li>Made with your brand</li>
      </ul>
      <form action="{% url 'users:paypal-sub' %}" method="POST">
        {% csrf_token %}
        <input value="Click" name="sub" value="4" hidden/>
        <button name="sub" value="3" style="color:white;background-color:#818a9d;" type="submit">Register!</button>
      </form>
    </div>
    <div class="element" style="color:#8C001A;">
      <div class="info">
        <h2>ENTERPRISE</h2>
        <p>Enterprise program for our services and products of highest quality and get access to every features of in our membership</p>
      </div>
      <span class="price">$999</span>
      <div class="period">
        <input type="radio" name="period" id="monthly" value="$12" checked />
        <label for="monthly">Monthly</label>
        <input type="radio" name="period" id="annualy" value="$8" />
        <label for="annualy">Annually</label>
      </div>
      <ul>
        <li>All Enterprise Capabilities</li>
        <li>Customized Analytics</li>
        <li>More services</li>
        <li>More products access</li>
      </ul>
      <form action="{% url 'users:paypal-sub' %}" method="POST">
        {% csrf_token %}
        <input value="Click" name="sub" value="4" hidden/>
        <button name="sub" value="4" style="color:white;background-color:#8C001A" type="submit">Register!</button>
      </form>

      
    </div>
  </div>
</section>

{% endblock content %}

templates/new_login.html
{% load i18n %}
{% load account socialaccount %}

{% block content %}



{% include 'head.html' %}   
{% load static %}
<style>
      
 .footer {
   left: 0;
   bottom: 0;
   width: 100%;
   background-color: #679141;
   color: white;
   text-align: center;
 }
</style>

<div class="bs-example">
    <nav class="navbar navbar-expand-md navbar-light " style="background-color: #679141">
        <a href="#" class="navbar-brand">
            <img src="{% static 'img/logo.png' %}" height="80" alt="NSMAR">
        </a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
                <a href="{% url 'account_signup' %}" class="nav-item nav-link active" style="color: white;">Become A Member</a>
            </div>
            <div class="navbar-nav ml-auto px-5">
              <ul id="topnav" class="navbar-nav  w-100 justify-content-left px-1 py-2" >
              <li class="nav-item" style="display: flex;align-items: flex-start;">
                <a class="nav-link" href="#" style="color: white;">
                    Already A Member?  Call Us We Are Here To Serve You </a>  

                    <a class="nav-link" href="?" style="color: white;">
                        <strong style="text-decoration: underline;font-size: larger;"> 555 123 4567</strong> </a>  
                    

              </li>                
              </ul>
            </div>
        </div>

    </nav>
    <nav class="navbar navbar-expand-md navbar-light bg-light" style="margin-top: -1%; display: flex; align-items: flex-end;">

      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar2Collapse">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse  justify-content-left navbar-collapse" id="navbar2Collapse">
        <div class="navbar-nav d-flex justify-content-end">
            <a href="#" class="hovel nav-item nav-link active" style="padding-right: 35px;padding-left: 30px;">
                Email us: 
                <strong style="text-decoration: underline;"> sales@nsamr.ca </strong>
            </a>
        </div>

    </div>
      <div class="collapse  justify-content-end navbar-collapse" id="navbar2Collapse">
          <div class="navbar-nav d-flex justify-content-end" style="margin-right: 5%;">

            <li class="nav-item" style="display: flex;align-items: flex-start;">
                <a class="nav-link" href="#" style="color: black;">
                    Not Yet A Member?  Call Us And Get The Help You Need </a>  

                    <a class="nav-link" href="?" style="color: black;">
                        <strong style="text-decoration: underline;font-size: larger;"> 145 145 1234 </strong> </a>  
                    

              </li>   
          </div>

      </div>

  </nav>
</div>







<div class="container register">
  <div class="row">
      <div class="col-md-3 register-left">
          <img src="{% static 'img/logo.png' %}" alt=""/>
          <p>National Sales & Marketing Resources</p><br>
          <small>Not a member?</small>
          <a name="" style="color: #3b5998;" href="{{ signup_url }}">Signup</a><br/>
      </div>
      <div class="col-md-9 register-right">

          <div class="tab-content" id="myTabContent">
              <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                  <h3 class="login-heading">Welcome Back</h3>
                  <form class="login" method="POST" action="{% url 'account_login' %}">
                    {% csrf_token %}

                  <div class="row register-form">
                      <div class="col-md-12">
                        {% if form.errors %}
                        {% for field in form %}
                        {% for error in field.errors %}
                            <p style="color: rgb(219, 44, 44);">{{ error|escape }}</p>
                        {% endfor %}
                     {% endfor %}
                    {% for error in form.non_field_errors %}
                    <p style="color: rgb(219, 44, 44);">{{ error|escape }}</p>
                    {% endfor %}
                {% endif %}   
                          <div class="form-group">
                              <input type="text" name="login" class="form-control" placeholder="Email *" required/>
                          </div>
                          <div class="form-group">
                              <input type="password" name="password" class="form-control" placeholder="Password *" required/>
                          </div>
                          {% if redirect_field_value %}
                          <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                          {% endif %}
                          <div>
                              <a href="{% url 'users:forget_password' %}">Forgot Password?</a>
                          </div>
                          <button id="myBtn" class="btnlogin">Login</button>
                      </div>

                  </div>

              </form>
              </div>

          </div>
      </div>
  </div>

</div>	
<div class="d-flex flex-column" style="margin-top: 6%;">
    <nav>
    </nav>
    <main class="flex-fill">
    </main>
    <footer class="footer">
        <p>Copyright Protected - NSMAR</p>
    </footer>
</div>
{% endblock %}